{
    "swagger": "2.0",
    "info": {
      "description": "API FOR EVENTPOINTS\n",
      "version": "0.0.1",
      "title": "EventPoints API",
      "contact": {
        "name": "OSWeekends",
        "url": "http://www.osweekends.com"
      }
    },
    "basePath": "/api/v1",
    "schemes": ["http"],
    "paths": {
      "/": {
        "get": {
          "tags": ["Ping"],
          "description": "Gets API up and runing messages\n",
          "produces": ["application/json"],
          "parameters": [],
          "responses": {
            "200": {
              "description": "API up and running message",
              "schema": {
                "$ref": "#/definitions/inline_response_200"
              }
            }
          }
        }
      },
      "/sources": {
        "get": {
          "tags": ["Sources"],
          "description": "Gets all sources for tech events\n",
          "produces": ["application/json"],
          "responses": {
            "200": {
              "description": "Sources propperly fetched",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/events_source"
                }
              }
            },
            "500": {
              "description": "Internal Server Error"
            }
          }
        }
      },
      "/events": {
        "get": {
          "tags": ["Events"],
          "description": "Gets all tech events\n",
          "produces": ["application/json"],
          "parameters": [
            {
            "in": "query",
            "name": "from",
            "type": "string",
            "description": "Fecha inicio  para filtrar eventos. Admite los siguientes formatos:\n - MM-DD-YYYY \n - millis"
            },
            {
              "in": "query",
              "name": "to",
              "type": "string",
              "description": "Fecha fin  para filtrar eventos.  Admite los siguientes formatos:\n - MM-DD-YYYY \n - millis"
              }
          ],
          "responses": {
            "200": {
              "description": "Events propperly fetched",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/inline_response_200_1"
                }
              }
            },
            "500": {
              "description": "Internal Server Error"
            }
          }
        }
      },
      "/events/{id}": {
        "get": {
          "tags": ["Events"],
          "description": "Gets tech event details by Id\n",
          "produces": ["application/json"],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "ID of event to fetch",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Event propperly fetched",
              "schema": {
                "$ref": "#/definitions/inline_response_200_1"
              }
            },
            "404": {
              "description": "Event not found"
            },
            "500": {
              "description": "Internal Server Error"
            }
          }
        }
      }
    },
    "definitions": {
      "events_price": {
        "properties": {
          "details": {
            "type": "string"
          },
          "is_free": {
            "type": "boolean"
          },
          "is_trusted": {
            "type": "boolean"
          }
        },
        "example": {
          "is_free": true,
          "details": "details",
          "is_trusted": true
        }
      },
      "events_source": {
        "properties": {
          "id": {
            "type": "string"
          },
          "logo": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "example": {
          "name": "name",
          "logo": "logo",
          "event_url": "event_url",
          "url": "url"
        }
      },
      "inline_response_200_1": {
        "properties": {
          "id": {
            "type": "string"
          },
          "source": {
            "$ref": "#/definitions/events_source"
          },
          "title": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "target_url": {
            "type": "string"
          },
          "host": {
            "type": "string"
          },
          "abstract": {
            "type": "string"
          },
          "abstract_details": {
            "type": "string"
          },
          "price": {
            "$ref": "#/definitions/events_price"
          },
          "datetime": {
            "type": "number"
          },
          "location": {
            "$ref": "#/definitions/events_location"
          },
          "date": {
            "type": "string"
          },
          "time": {
            "type": "string"
          }          
        },
        "example": {
          "date": "10/11/2018",
          "time": "19:00",
          "datetime": 1542304800000,
          "price": {
            "is_free": true,
            "details": "details",
            "is_trusted": true
          },
          "target_url": "target_url",
          "location": {
            "address": "notes",            
            "name": "name",
            "query": "40.444145,-3.667261",
            "lat": "40.444145",
            "lng": "-3.667261"
          },
          "abstract": "abstract",
          "source": {
            "name": "name",
            "logo": "logo",
            "id": "meetup",            
            "url": "url"
          },
          "id": "id",
          "group": "Grupo del evento",
          "abstract_details": "abstract_details",
          "title": "title"
        }
      },
      "inline_response_200": {
        "required": ["message"],
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "message"
        }
      },
      "events_location": {
        "properties": {
          "lat": {
            "type": "string"
          },
          "lng": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "query": {
            "type": "string"
          }
        },
        "example": {
          "name": "IBM Client Center Madrid",
            "address": "Calle Corazón de María, 44 (esquina con Santa Hortensia)",
            "query": "40.444145,-3.667261",
            "lat": "40.444145",
            "lng": "-3.667261"
        }
      }
    }
  }